

    name: run-script
    on:
      workflow_dispatch:
      schedule:
    # * is a special character in YAML so you have to quote this string
      - cron:  "*/2 * * * *"

    jobs:
      myrun:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: script
            run: |
              python3 script.py ${{ github.run_number }}
