name: Test Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Action
        # we can give directory path that contains action.yaml or repo address in username/repository_name@version format
        # in our case it would be nashmaniac/create-issue-action@v1.0 where v1.0 is the version of action
        # for now we will give directory path. The directory must contain action.yaml
        uses: ./
        id: bc-copy-ccm
        env:
          REPOSITORY: ldahlke/schulcloud-server
        # pass user input as arguments
        with:
          version: 26.10.4
          tags: schulcloud/schulcloud-server:26.10.4, schulcloud/schulcloud-server:26.10, schulcloud/schulcloud-server:latest
          labels: org.opencontainers.image.title=schulcloud-server,  org.opencontainers.image.description=HPI Schul-Cloud Core Server, org.opencontainers.image.url=https://github.com/hpi-schul-cloud/schulcloud-server
          target:  ldahlke/ld-ccm
      - name: Echo Output
        run: |
          echo "Outputs - ${{ steps.bc-copy-ccm.outputs.filescopied }}"